#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    type: com.alibaba.druid.pool.DruidDataSource

##mybatisplus配置
#mybatis:
#  table:
#    auto: update
#    #create	    系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
#    #update	    系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
#    #none 		系统不做任何处理。
#    #add		新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
#  model:
#    pack: com.jingfeng999.blog.po #扫描用于创建表的对象的包名，多个包用“,”隔开
#  database:
#    type: mysql #数据库类型 目前只支持mysql
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml

#日志配置
logging:
  level:
    root: info
    com.jingfeng999.bolg: debug
  file:
    name: log/blog-dev.log